services:
  - type: web
    name: liver-disease-prediction
    python:
      version: "3.10.13"
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app